src := \
	../Nand/Nand.v \
	../Not/Not.v \
	../And/And.v \
	../Xor/Xor.v \
	../Or/Or.v \
	../HalfAdder/HalfAdder.v \
	../FullAdder/FullAdder.v \
	AddN.v \
	Add16.v
test_bench := Test.v

include ../build.mk
