src := \
	../Nand/Nand.v \
	../Not/Not.v \
	../And/And.v \
	../Xor/Xor.v \
	../Or/Or.v \
	../HalfAdder/HalfAdder.v \
	../FullAdder/FullAdder.v \
	../Add16/AddN.v \
	IncN.v \
	Inc16.v
test_bench := Test.v

include ../build.mk
