src := \
	../Nand/Nand.v \
	../Xor/Xor.v \
	../Not/Not.v \
	../Not16/NotN.v \
	../And/And.v \
	../And16/AndN.v \
	../Mux/Mux.v \
	../Mux16/MuxN.v \
	../Or/Or.v \
	../Or8Way/OrNWay.v \
	../HalfAdder/HalfAdder.v \
	../FullAdder/FullAdder.v \
	../Add16/AddN.v \
	ALUN.v \
	ALU.v
test_bench := Test.v

include ../build.mk
